apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-scheduler
  template:
    metadata:
      labels:
        app: appointment-scheduler
    spec:
      containers:
      - name: appointment-scheduler
        image: pramidha/appointment-scheduler:latest
        ports:
        - containerPort: 5000
