apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  type: NodePort
  selector:
    app: appointment-scheduler
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008
